version: '3.9'

services:
  postgres: postgres:16-alpine
  restart: unless-stopped
  ports:
    - ${DATABASE_PORT}:5432
  environment:
    POSTGRES_USER: ${DATABASE_USER}
    POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    POSTGRES_DB: ${DATABASE_DB}
  volumes:
    - ./db-data:/var/lib/postgresql/data
